openapi: 3.0.0
info:
  title: Positive Affirmations REST API
  description: Specification document defining all the functionality of the REST API for Positive Affirmations application
  version: 0.1.0
servers:
  - url: http://positive-affirmations.quadimension.com/api/v1
    description: Main (production) server
  - url: http://localhost:3333/api/v1
    description: Internal staging server for testing
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
