openapi: 3.0.0
info:
  title: Positive Affirmations REST API
  description: Specification document defining all the functionality of the REST API for Positive Affirmations application
  version: 0.1.0

servers:
  - url: http://positive-affirmations.quadimension.com/api/v1
    description: Main (production) server
  - url: http://localhost:3333/api/v1
    description: Internal staging server for testing

paths:
  /members:
    post:
      summary: Creates a new member with given parameters
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMemberCommand'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateMemberCommandResponseData'

  /members/{memberId}:
    get:
      summary: Returns a member by ID.
      parameters:
        - in: path
          name: memberId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'

components:
  schemas:
    CreateMemberCommand:
      properties:
        name:
          type: string
        nickName:
          type: string
      required:
        - name
    CreateMemberCommandResponseData:
      $ref: '#/components/schemas/Member'

    Member:
      properties:
        id:
          type: integer
        name:
          type: string
        nickName:
          type: string
      required:
        - id
        - name