openapi: 3.0.0
info:
  title: Positive Affirmations REST API
  description: Specification document defining all the functionality of the REST API for Positive Affirmations application
  version: 0.1.0

servers:
  - url: http://positive-affirmations.quadimension.com/api/v1
    description: Main (production) server
  - url: http://localhost:3333/api/v1
    description: Internal staging server for testing

paths:
  /members:
    post:
      tags:
        - members
      summary: Creates a new member with given parameters
      operationId: createMemberCommand
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMemberCommand'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateMemberCommandResponseData'

  /members/{memberId}:
    get:
      tags:
        - members
      summary: Returns a member's profile details
      parameters:
        - in: path
          name: memberId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'

  /files:
    post:
      tags:
        - files
      summary: Creates a signed url for uploading a given file
      operationId: createFileUploadUrlCommand
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateFileUploadUrlCommand'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateFileUploadUrlCommandResponseData'

components:
  securitySchemes:
    oAuth:
      type: oauth2
      description: This API uses OAuth 2 with the authorizationCode grant flow. This grant flow is required for mobile apps as [specified here](https://developers.google.com/identity/protocols/oauth2/native-app#exchange-authorization-code).
      flows:
        authorizationCode:
          authorizationUrl: https://api.example.com/oauth2/authorize
          tokenUrl: https://api.example.com/oauth2/authorize
          scopes:
            read_member: Members reading their own details and other members' details.
            read_members: Read details of all members.
            update_member: Members updating their own details.
            write_affirmations: Create new affirmations
            update_affirmation: Update affirmations created by yourself
            update_affirmations: Update any affirmation

  schemas:
    ApiResponse:
      properties:
        code:
          type: string
        message:
          type: string
    Member:
      properties:
        id:
          type: integer
        name:
          type: string
        nickName:
          type: string
        profilePicture:
          $ref: '#/components/schemas/FileDto'
        selfSummary:
          type: string
        totalAffirmations:
          type: integer
          default: 0
        totalLetters:
          type: integer
          default: 0
        totalReaffirmations:
          type: integer
          default: 0
        createdOn:
          type: string
          format: date-time
        modifiedOn:
          type: string
          format: date-time
      required:
        - id
        - name
        - createdOn
        - modifiedOn

    FileDto:
      properties:
        id:
          type: string
        contentType:
          description: See [object metadata](https://cloud.google.com/storage/docs/metadata) and more specifically, [content type metadata](https://cloud.google.com/storage/docs/metadata#content-type) to learn more.
          type: string
          enum:
            - application/json
            - application/mp4
            - video/mp4
            - text/plain
            - image/jpeg
            - image/png
        path:
          description: The full path (starting at the root) of the file in the bucket
          type: string
        sizeInBytes:
          type: integer
        signedUrlType:
          type: string
          description: Does this URL allow downloading or uploading?
          enum:
            - upload
            - download
        signedUrl:
          type: string
      required:
        - id
        - contentType
        - path
        - signedUrlType
        - signedUrl

    CreateMemberCommand:
      properties:
        name:
          type: string
        nickName:
          type: string
      required:
        - name
    CreateMemberCommandResponseData:
      properties:
        apiResponse:
          $ref: '#/components/schemas/ApiResponse'
        data:
          $ref: '#/components/schemas/Member'
    UpdateMemberCommand:
      properties:
        name:
          type: string
        nickName:
          type: string
        selfSummary:
          type: string

    CreateFileUploadUrlCommand:
      properties:
        fileName:
          type: string
        contentType:
          type: string
          enum:
            - application/json
            - application/mp4
            - video/mp4
            - text/plain
            - image/jpeg
            - image/png
        sizeInBytes:
          type: integer
      required:
        - fileName
        - contentType
        - sizeInBytes
    CreateFileUploadUrlCommandResponseData:
      properties:
        apiResponse:
          $ref: '#/components/schemas/ApiResponse'
        data:
          $ref: '#/components/schemas/FileDto'
