name: mobile_app
description: Positive Affirmations mobile app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.0+13

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  bloc: ^7.2.1
  hydrated_bloc: ^7.1.0
  formz: ^0.4.0
  uuid: ^3.0.4
  flutter_bloc: ^7.3.0
  path_provider: ^2.0.5
  font_awesome_flutter: ^9.1.0
  animated_text_kit: ^4.2.1
  repository:
    path: packages/repository
  image_picker: ^0.8.4+2
  flutter_local_notifications: ^9.0.0
  workmanager: ^0.4.1

dev_dependencies:
  bloc_test: ^8.2.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.7
  mocktail: ^0.1.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  #  assets:
  #    - google_fonts/

  fonts:
    - family: Birthstone
      fonts:
        - asset: assets/fonts/Birthstone-Regular.ttf
          style: normal
    - family: Gemunu Libre
      fonts:
        - asset: assets/fonts/GemunuLibre-ExtraLight.ttf
          style: normal
          weight: 200
        - asset: assets/fonts/GemunuLibre-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/GemunuLibre-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/GemunuLibre-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/GemunuLibre-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/GemunuLibre-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/GemunuLibre-ExtraBold.ttf
          style: normal
          weight: 800
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          style: normal
          weight: 100
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          style: normal
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          style: normal
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          style: normal
          weight: 900
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
          style: italic
          weight: 900
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
