name: Deploy to Play Store
on:
  workflow_dispatch:
    # Enable manual run
    inputs:
      lane:
        description: 'Fastlane lane to use (internal OR promote_to_production OR production)'
        required: true
        default: 'internal'
#  push:
#    # Sequence of patterns matched against refs/tags
#    tags:
#      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

# TODO: Add reference to working solutin

jobs:
  fastlane-deploy:
    runs-on: ubuntu-18.04
    steps:
      # Set up Flutter.
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@v1.5.0
        with:
          channel: master
      - run: flutter doctor -v


      - name: Checkout application code
        uses: actions/checkout@v2

      - run: flutter pub get
        working-directory: src/mobile_app

      # Setup Ruby, Bundler, and Gemfile dependencies
      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true
          working-directory: src/mobile_app/android

      - name: Configure Keystore
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
        working-directory: src/mobile_app/android

      - name: Set up Firebase and Google Play config jsons
        run: |
          echo "$FIREBASE_GOOGLE_SERVICES_JSON" | base64 -d > app/google-services.json
          echo "$PLAY_STORE_CONFIG_JSON" | base64 -d > app/play-store-config.json
        env:
          FIREBASE_GOOGLE_SERVICES_JSON: ${{ secrets.FIREBASE_GOOGLE_SERVICES_JSON }}
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        working-directory: src/mobile_app/android

      # Build and deploy with Fastlane (by default, to beta track) 🚀.
      # Naturally, promote_to_production only deploys.
      - run: bundle exec fastlane ${{ github.event.inputs.lane || 'internal' }}
        env:
          PLAY_STORE_CONFIG_JSON: app/play-store-config.json
          FIREBASE_APP_DIST_APP: ${{ secrets.FIREBASE_APP_DIST_APP }}
          FIREBASE_APP_DIST_TESTERS: ${{ secrets.FIREBASE_APP_DIST_TESTERS }}
        working-directory: src/mobile_app/android
