# This is a basic workflow to help you get started with Actions

name: Flutter CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ mobile/user_signup_flow ]
  pull_request:
    branches: [ mobile/user_signup_flow ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches: [ mobile/user_signup_flow ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    container:
      image: gcr.io/positive-affirmations-313800/droid-deploy-env:latest
      credentials:
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: DEBUG
        run: ls

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Setup Java environment
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # Setup flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
#          version: '2.12.0'


      - name: Get flutter dependencies
        working-directory: ./src/mobile_app
        run: flutter pub get

      - name: Check for any formatting issues in the code.
        working-directory: ./src/mobile_app
        run: flutter format --set-exit-if-changed .

      - name: Statically analyze the Dart code for any errors
        working-directory: ./src/mobile_app
        run: flutter analyze .

      - name: Run widget tests for our flutter project.
        working-directory: ./src/mobile_app
        run: flutter test

      - name: Set up Firebase credential
        working-directory: ./src/mobile_app
        run: echo ${{ secrets.FIREBASE_GOOGLE_SERVICES_JSON }} | base64 -d > android/app/google-services.json

      - name: Build DEBUG APK.
        working-directory: ./src/mobile_app
        run: flutter build apk --debug
